# Generated by Django 5.0.2 on 2024-02-23 17:44

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('f_contact', models.BigIntegerField()),
                ('f_message', models.TextField()),
                ('f_status', models.CharField(choices=[('Show', 'Show'), ('Hide', 'Hide')], max_length=20)),
                ('focdate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('rtid', models.IntegerField()),
                ('r_rate', models.IntegerField()),
                ('r_cdate', models.DateTimeField()),
                ('r_udate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_t_id', models.IntegerField()),
                ('s_slot', models.CharField(max_length=20)),
                ('s_cdate', models.DateTimeField()),
                ('s_udate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('a_img', models.ImageField(blank=True, null=True, upload_to='media/admin_images/')),
                ('a_lastseen', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_t_id', models.IntegerField(blank=True, null=True)),
                ('b_slot_id', models.CharField(max_length=20)),
                ('b_vehicleno', models.CharField(max_length=20)),
                ('b_contact', models.BigIntegerField()),
                ('b_date', models.DateField()),
                ('b_startdate', models.CharField(max_length=20)),
                ('b_enddate', models.CharField(max_length=20)),
                ('b_totaltime', models.CharField(max_length=20)),
                ('b_amount', models.IntegerField()),
                ('b_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Complete', 'Complete')], max_length=20)),
                ('b_udate', models.DateTimeField()),
                ('b_u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
